language: node_js
sudo: false
node_js:
  - "0.10"
  - "0.12"
services:
  - mongodb
before_script:
  - sleep 10
  - echo mongo mongo_travis
script: "make travis"
after_script: "npm install coveralls && cat ./coverage/lcov.info | coveralls"
